const recipes = [
    {
        id: 1,
        name: 'Margherita Pizza',
        createdBy: 'Jane',
        rating: 4, // out of 5
        ingredients: [
            '1 pizza dough',
            '1/2 cup pizza sauce',
            '1 1/2 cups mozzarella cheese, shredded',
            'Fresh basil leaves for garnish',
            'Salt and pepper to taste',
        ],
        steps: [
            'Preheat your oven to 475°F (245°C).',
            'Roll out the pizza dough on a floured surface to your desired thickness.',
            'Transfer the dough to a pizza stone or baking sheet.',
            'Spread pizza sauce evenly over the dough, leaving a small border around the edges.',
            'Sprinkle mozzarella cheese over the sauce.',
            'Season with salt and pepper to taste.',
            'Bake in the preheated oven for 12-15 minutes or until the crust is golden and the cheese is bubbly.',
            'Remove from the oven, garnish with fresh basil leaves, and slice. Enjoy!',
        ],
        category: 'snack', // breakfast, dinner, lunch, veg, non-veg
        difficulty: 1, // out of 3
        image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
    },
    {
        id: 2,
        name: 'Spaghetti Carbonara',
        createdBy: 'John',
        rating: 5, // out of 5
        ingredients: [
            '8 oz (225g) spaghetti',
            '2 large eggs',
            '1 cup grated Pecorino Romano cheese',
            '4 oz (115g) pancetta or guanciale, diced',
            '2 cloves garlic, minced',
            'Freshly ground black pepper',
            'Salt to taste',
        ],
        steps: [
            'Cook spaghetti in a large pot of salted boiling water until al dente. Drain and set aside.',
            'In a bowl, whisk together eggs, grated Pecorino Romano cheese, and a generous amount of freshly ground black pepper.',
            'In a large skillet, saut&eacute; diced pancetta or guanciale until crispy. Add minced garlic and cook briefly.',
            'Add cooked spaghetti to the skillet with the pancetta and garlic. Toss to combine.',
            'Remove the skillet from heat and quickly pour the egg and cheese mixture over the pasta. Toss vigorously to create a creamy sauce.',
            'If the sauce is too thick, you can add a bit of pasta cooking water to achieve the desired consistency.',
            'Season with salt if needed, and serve immediately. Enjoy!',
        ],
        category: 'dinner',
        difficulty: 2,
        image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2071&q=80',
    },
    {
        id: 3,
        name: 'Chicken Alfredo',
        createdBy: 'Sarah',
        rating: 4.5,
        ingredients: [
            '8 oz fettuccine pasta',
            '2 boneless, skinless chicken breasts',
            '2 cups heavy cream',
            '1/2 cup grated Parmesan cheese',
            '2 cloves garlic, minced',
            '2 tablespoons butter',
            'Salt and pepper to taste',
        ],
        steps: [
            'Cook fettuccine pasta according to package instructions. Drain and set aside.',
            'Season chicken breasts with salt and pepper.',
            'In a large skillet, melt butter over medium-high heat. Add chicken breasts and cook until browned and cooked through. Remove from skillet and slice.',
            'In the same skillet, add minced garlic and cook briefly until fragrant.',
            'Pour in heavy cream and grated Parmesan cheese. Stir until the sauce thickens.',
            'Return sliced chicken to the skillet and simmer for a few minutes.',
            'Serve the chicken and Alfredo sauce over cooked fettuccine pasta. Enjoy!',
        ],
        category: 'dinner',
        difficulty: 2,
        image: 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
    },
    {
        id: 4,
        name: 'Avocado Toast',
        createdBy: 'David',
        rating: 4.2,
        ingredients: [
            '2 slices of whole-grain bread',
            '1 ripe avocado',
            '1/2 lemon, juiced',
            'Salt and black pepper to taste',
            'Red pepper flakes (optional)',
            'Poached egg (optional)',
        ],
        steps: [
            'Toast two slices of whole-grain bread until they are crispy and golden brown.',
            'While the bread is toasting, cut a ripe avocado in half and remove the pit.',
            'Scoop the avocado flesh into a bowl and mash it with a fork.',
            'Add freshly squeezed lemon juice, salt, and black pepper to the mashed avocado. Mix well.',
            'Spread the avocado mixture evenly onto the toasted bread slices.',
            'If desired, sprinkle with red pepper flakes for some heat or add a poached egg on top for extra protein.',
            'Serve immediately. Enjoy your avocado toast!',
        ],
        category: 'breakfast',
        difficulty: 1,
        image: 'https://images.unsplash.com/photo-1490091119006-59eb16fe739d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1932&q=80',
    },
    {
        id: 5,
        name: 'Mushroom Risotto',
        createdBy: 'Emily',
        rating: 4.7,
        ingredients: [
            '1 1/2 cups Arborio rice',
            '8 oz mushrooms, sliced',
            '4 cups chicken or vegetable broth, hot',
            '1 cup dry white wine',
            '1/2 cup grated Parmesan cheese',
            '1 small onion, finely chopped',
            '2 cloves garlic, minced',
            '2 tablespoons butter',
            '2 tablespoons olive oil',
            'Salt and black pepper to taste',
        ],
        steps: [
            'In a large skillet, heat olive oil and 1 tablespoon of butter over medium heat.',
            'Add chopped onion and garlic. Sauté until translucent.',
            'Add sliced mushrooms and cook until they release their moisture and turn golden brown.',
            'Stir in Arborio rice and cook for a couple of minutes until the rice is well-coated with oil.',
            'Pour in the dry white wine and stir until it&apos;s mostly absorbed by the rice.',
            'Begin adding hot chicken or vegetable broth, one ladle at a time, stirring constantly. Wait until the liquid is mostly absorbed before adding more broth.',
            'Continue this process until the rice is creamy and cooked to your desired tenderness. It will take about 18-20 minutes.',
            'Stir in grated Parmesan cheese and remaining butter. Season with salt and black pepper to taste.',
            'Serve the mushroom risotto hot. Enjoy!',
        ],
        category: 'lunch',
        difficulty: 2,
        image: 'https://images.unsplash.com/photo-1633964913295-ceb43826e7c9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
    },
    {
        id: 6,
        name: 'Veggie Wrap',
        createdBy: 'Sophia',
        rating: 4.3,
        ingredients: [
            '1 large whole-wheat tortilla',
            '1/2 cup hummus',
            '1/2 cup mixed salad greens',
            '1/4 cup sliced cucumber',
            '1/4 cup sliced bell peppers (red, yellow, or green)',
            '1/4 cup shredded carrots',
            '1/4 cup cherry tomatoes, halved',
            '1/4 cup feta cheese, crumbled',
            'Salt and black pepper to taste',
        ],
        steps: [
            'Lay out a large whole-wheat tortilla on a clean surface.',
            'Spread a generous layer of hummus evenly over the tortilla.',
            'Place mixed salad greens in the center of the tortilla, leaving some space on the sides.',
            'Add sliced cucumber, bell peppers, shredded carrots, and cherry tomatoes on top of the greens.',
            'Sprinkle crumbled feta cheese over the vegetables.',
            'Season with salt and black pepper to taste.',
            'Fold in the sides of the tortilla and then roll it up tightly from the bottom to create a wrap.',
            'Cut the veggie wrap in half diagonally, and it&apos;s ready to serve. Enjoy!',
        ],
        category: 'lunch',
        difficulty: 1,
        image: 'https://plus.unsplash.com/premium_photo-1664648119278-15e9133714c4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
    },
];

export default recipes;
